package com.jiyun.a123.myapplication2.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jiyun.a123.myapplication2.bean.ResultBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RESULT_BEAN".
*/
public class ResultBeanDao extends AbstractDao<ResultBean, Long> {

    public static final String TABLENAME = "RESULT_BEAN";

    /**
     * Properties of entity ResultBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Ssid = new Property(0, Long.class, "ssid", true, "sss");
        public final static Property Xuan = new Property(1, boolean.class, "xuan", false, "XUAN");
        public final static Property Country = new Property(2, String.class, "country", false, "COUNTRY");
        public final static Property Piao_id = new Property(3, String.class, "piao_id", false, "PIAO_ID");
        public final static Property Album_1000_1000 = new Property(4, String.class, "album_1000_1000", false, "ALBUM_1000_1000");
        public final static Property Korean_bb_song = new Property(5, String.class, "korean_bb_song", false, "KOREAN_BB_SONG");
        public final static Property Pic_huge = new Property(6, String.class, "pic_huge", false, "PIC_HUGE");
        public final static Property All_rate = new Property(7, String.class, "all_rate", false, "ALL_RATE");
        public final static Property Song_source = new Property(8, String.class, "song_source", false, "SONG_SOURCE");
        public final static Property Song_id = new Property(9, String.class, "song_id", false, "SONG_ID");
        public final static Property Album_500_500 = new Property(10, String.class, "album_500_500", false, "ALBUM_500_500");
        public final static Property Rank = new Property(11, String.class, "rank", false, "RANK");
        public final static Property Pic_premium = new Property(12, String.class, "pic_premium", false, "PIC_PREMIUM");
        public final static Property Album_800_800 = new Property(13, String.class, "album_800_800", false, "ALBUM_800_800");
        public final static Property Info = new Property(14, String.class, "info", false, "INFO");
        public final static Property Area = new Property(15, String.class, "area", false, "AREA");
        public final static Property Si_proxycompany = new Property(16, String.class, "si_proxycompany", false, "SI_PROXYCOMPANY");
        public final static Property Has_mv_mobile = new Property(17, int.class, "has_mv_mobile", false, "HAS_MV_MOBILE");
        public final static Property Is_new = new Property(18, String.class, "is_new", false, "IS_NEW");
        public final static Property Author = new Property(19, String.class, "author", false, "AUTHOR");
        public final static Property Resource_type = new Property(20, String.class, "resource_type", false, "RESOURCE_TYPE");
        public final static Property Has_filmtv = new Property(21, String.class, "has_filmtv", false, "HAS_FILMTV");
        public final static Property All_artist_ting_uid = new Property(22, String.class, "all_artist_ting_uid", false, "ALL_ARTIST_TING_UID");
        public final static Property Artist_id = new Property(23, String.class, "artist_id", false, "ARTIST_ID");
        public final static Property Versions = new Property(24, String.class, "versions", false, "VERSIONS");
        public final static Property Publishtime = new Property(25, String.class, "publishtime", false, "PUBLISHTIME");
        public final static Property Style = new Property(26, String.class, "style", false, "STYLE");
        public final static Property Album_id = new Property(27, String.class, "album_id", false, "ALBUM_ID");
        public final static Property Album_no = new Property(28, String.class, "album_no", false, "ALBUM_NO");
        public final static Property Resource_type_ext = new Property(29, String.class, "resource_type_ext", false, "RESOURCE_TYPE_EXT");
        public final static Property Del_status = new Property(30, String.class, "del_status", false, "DEL_STATUS");
        public final static Property Hot = new Property(31, String.class, "hot", false, "HOT");
        public final static Property Toneid = new Property(32, String.class, "toneid", false, "TONEID");
        public final static Property Title = new Property(33, String.class, "title", false, "TITLE");
        public final static Property Pic_big = new Property(34, String.class, "pic_big", false, "PIC_BIG");
        public final static Property Havehigh = new Property(35, int.class, "havehigh", false, "HAVEHIGH");
        public final static Property Charge = new Property(36, int.class, "charge", false, "CHARGE");
        public final static Property Pic_radio = new Property(37, String.class, "pic_radio", false, "PIC_RADIO");
        public final static Property Learn = new Property(38, int.class, "learn", false, "LEARN");
        public final static Property Pic_s500 = new Property(39, String.class, "pic_s500", false, "PIC_S500");
        public final static Property All_artist_id = new Property(40, String.class, "all_artist_id", false, "ALL_ARTIST_ID");
        public final static Property Pic_small = new Property(41, String.class, "pic_small", false, "PIC_SMALL");
        public final static Property Album_title = new Property(42, String.class, "album_title", false, "ALBUM_TITLE");
    }


    public ResultBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ResultBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RESULT_BEAN\" (" + //
                "\"sss\" INTEGER PRIMARY KEY ," + // 0: ssid
                "\"XUAN\" INTEGER NOT NULL ," + // 1: xuan
                "\"COUNTRY\" TEXT," + // 2: country
                "\"PIAO_ID\" TEXT," + // 3: piao_id
                "\"ALBUM_1000_1000\" TEXT," + // 4: album_1000_1000
                "\"KOREAN_BB_SONG\" TEXT," + // 5: korean_bb_song
                "\"PIC_HUGE\" TEXT," + // 6: pic_huge
                "\"ALL_RATE\" TEXT," + // 7: all_rate
                "\"SONG_SOURCE\" TEXT," + // 8: song_source
                "\"SONG_ID\" TEXT," + // 9: song_id
                "\"ALBUM_500_500\" TEXT," + // 10: album_500_500
                "\"RANK\" TEXT," + // 11: rank
                "\"PIC_PREMIUM\" TEXT," + // 12: pic_premium
                "\"ALBUM_800_800\" TEXT," + // 13: album_800_800
                "\"INFO\" TEXT," + // 14: info
                "\"AREA\" TEXT," + // 15: area
                "\"SI_PROXYCOMPANY\" TEXT," + // 16: si_proxycompany
                "\"HAS_MV_MOBILE\" INTEGER NOT NULL ," + // 17: has_mv_mobile
                "\"IS_NEW\" TEXT," + // 18: is_new
                "\"AUTHOR\" TEXT," + // 19: author
                "\"RESOURCE_TYPE\" TEXT," + // 20: resource_type
                "\"HAS_FILMTV\" TEXT," + // 21: has_filmtv
                "\"ALL_ARTIST_TING_UID\" TEXT," + // 22: all_artist_ting_uid
                "\"ARTIST_ID\" TEXT," + // 23: artist_id
                "\"VERSIONS\" TEXT," + // 24: versions
                "\"PUBLISHTIME\" TEXT," + // 25: publishtime
                "\"STYLE\" TEXT," + // 26: style
                "\"ALBUM_ID\" TEXT," + // 27: album_id
                "\"ALBUM_NO\" TEXT," + // 28: album_no
                "\"RESOURCE_TYPE_EXT\" TEXT," + // 29: resource_type_ext
                "\"DEL_STATUS\" TEXT," + // 30: del_status
                "\"HOT\" TEXT," + // 31: hot
                "\"TONEID\" TEXT," + // 32: toneid
                "\"TITLE\" TEXT," + // 33: title
                "\"PIC_BIG\" TEXT," + // 34: pic_big
                "\"HAVEHIGH\" INTEGER NOT NULL ," + // 35: havehigh
                "\"CHARGE\" INTEGER NOT NULL ," + // 36: charge
                "\"PIC_RADIO\" TEXT," + // 37: pic_radio
                "\"LEARN\" INTEGER NOT NULL ," + // 38: learn
                "\"PIC_S500\" TEXT," + // 39: pic_s500
                "\"ALL_ARTIST_ID\" TEXT," + // 40: all_artist_id
                "\"PIC_SMALL\" TEXT," + // 41: pic_small
                "\"ALBUM_TITLE\" TEXT);"); // 42: album_title
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RESULT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ResultBean entity) {
        stmt.clearBindings();
 
        Long ssid = entity.getSsid();
        if (ssid != null) {
            stmt.bindLong(1, ssid);
        }
        stmt.bindLong(2, entity.getXuan() ? 1L: 0L);
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(3, country);
        }
 
        String piao_id = entity.getPiao_id();
        if (piao_id != null) {
            stmt.bindString(4, piao_id);
        }
 
        String album_1000_1000 = entity.getAlbum_1000_1000();
        if (album_1000_1000 != null) {
            stmt.bindString(5, album_1000_1000);
        }
 
        String korean_bb_song = entity.getKorean_bb_song();
        if (korean_bb_song != null) {
            stmt.bindString(6, korean_bb_song);
        }
 
        String pic_huge = entity.getPic_huge();
        if (pic_huge != null) {
            stmt.bindString(7, pic_huge);
        }
 
        String all_rate = entity.getAll_rate();
        if (all_rate != null) {
            stmt.bindString(8, all_rate);
        }
 
        String song_source = entity.getSong_source();
        if (song_source != null) {
            stmt.bindString(9, song_source);
        }
 
        String song_id = entity.getSong_id();
        if (song_id != null) {
            stmt.bindString(10, song_id);
        }
 
        String album_500_500 = entity.getAlbum_500_500();
        if (album_500_500 != null) {
            stmt.bindString(11, album_500_500);
        }
 
        String rank = entity.getRank();
        if (rank != null) {
            stmt.bindString(12, rank);
        }
 
        String pic_premium = entity.getPic_premium();
        if (pic_premium != null) {
            stmt.bindString(13, pic_premium);
        }
 
        String album_800_800 = entity.getAlbum_800_800();
        if (album_800_800 != null) {
            stmt.bindString(14, album_800_800);
        }
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(15, info);
        }
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(16, area);
        }
 
        String si_proxycompany = entity.getSi_proxycompany();
        if (si_proxycompany != null) {
            stmt.bindString(17, si_proxycompany);
        }
        stmt.bindLong(18, entity.getHas_mv_mobile());
 
        String is_new = entity.getIs_new();
        if (is_new != null) {
            stmt.bindString(19, is_new);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(20, author);
        }
 
        String resource_type = entity.getResource_type();
        if (resource_type != null) {
            stmt.bindString(21, resource_type);
        }
 
        String has_filmtv = entity.getHas_filmtv();
        if (has_filmtv != null) {
            stmt.bindString(22, has_filmtv);
        }
 
        String all_artist_ting_uid = entity.getAll_artist_ting_uid();
        if (all_artist_ting_uid != null) {
            stmt.bindString(23, all_artist_ting_uid);
        }
 
        String artist_id = entity.getArtist_id();
        if (artist_id != null) {
            stmt.bindString(24, artist_id);
        }
 
        String versions = entity.getVersions();
        if (versions != null) {
            stmt.bindString(25, versions);
        }
 
        String publishtime = entity.getPublishtime();
        if (publishtime != null) {
            stmt.bindString(26, publishtime);
        }
 
        String style = entity.getStyle();
        if (style != null) {
            stmt.bindString(27, style);
        }
 
        String album_id = entity.getAlbum_id();
        if (album_id != null) {
            stmt.bindString(28, album_id);
        }
 
        String album_no = entity.getAlbum_no();
        if (album_no != null) {
            stmt.bindString(29, album_no);
        }
 
        String resource_type_ext = entity.getResource_type_ext();
        if (resource_type_ext != null) {
            stmt.bindString(30, resource_type_ext);
        }
 
        String del_status = entity.getDel_status();
        if (del_status != null) {
            stmt.bindString(31, del_status);
        }
 
        String hot = entity.getHot();
        if (hot != null) {
            stmt.bindString(32, hot);
        }
 
        String toneid = entity.getToneid();
        if (toneid != null) {
            stmt.bindString(33, toneid);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(34, title);
        }
 
        String pic_big = entity.getPic_big();
        if (pic_big != null) {
            stmt.bindString(35, pic_big);
        }
        stmt.bindLong(36, entity.getHavehigh());
        stmt.bindLong(37, entity.getCharge());
 
        String pic_radio = entity.getPic_radio();
        if (pic_radio != null) {
            stmt.bindString(38, pic_radio);
        }
        stmt.bindLong(39, entity.getLearn());
 
        String pic_s500 = entity.getPic_s500();
        if (pic_s500 != null) {
            stmt.bindString(40, pic_s500);
        }
 
        String all_artist_id = entity.getAll_artist_id();
        if (all_artist_id != null) {
            stmt.bindString(41, all_artist_id);
        }
 
        String pic_small = entity.getPic_small();
        if (pic_small != null) {
            stmt.bindString(42, pic_small);
        }
 
        String album_title = entity.getAlbum_title();
        if (album_title != null) {
            stmt.bindString(43, album_title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ResultBean entity) {
        stmt.clearBindings();
 
        Long ssid = entity.getSsid();
        if (ssid != null) {
            stmt.bindLong(1, ssid);
        }
        stmt.bindLong(2, entity.getXuan() ? 1L: 0L);
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(3, country);
        }
 
        String piao_id = entity.getPiao_id();
        if (piao_id != null) {
            stmt.bindString(4, piao_id);
        }
 
        String album_1000_1000 = entity.getAlbum_1000_1000();
        if (album_1000_1000 != null) {
            stmt.bindString(5, album_1000_1000);
        }
 
        String korean_bb_song = entity.getKorean_bb_song();
        if (korean_bb_song != null) {
            stmt.bindString(6, korean_bb_song);
        }
 
        String pic_huge = entity.getPic_huge();
        if (pic_huge != null) {
            stmt.bindString(7, pic_huge);
        }
 
        String all_rate = entity.getAll_rate();
        if (all_rate != null) {
            stmt.bindString(8, all_rate);
        }
 
        String song_source = entity.getSong_source();
        if (song_source != null) {
            stmt.bindString(9, song_source);
        }
 
        String song_id = entity.getSong_id();
        if (song_id != null) {
            stmt.bindString(10, song_id);
        }
 
        String album_500_500 = entity.getAlbum_500_500();
        if (album_500_500 != null) {
            stmt.bindString(11, album_500_500);
        }
 
        String rank = entity.getRank();
        if (rank != null) {
            stmt.bindString(12, rank);
        }
 
        String pic_premium = entity.getPic_premium();
        if (pic_premium != null) {
            stmt.bindString(13, pic_premium);
        }
 
        String album_800_800 = entity.getAlbum_800_800();
        if (album_800_800 != null) {
            stmt.bindString(14, album_800_800);
        }
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(15, info);
        }
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(16, area);
        }
 
        String si_proxycompany = entity.getSi_proxycompany();
        if (si_proxycompany != null) {
            stmt.bindString(17, si_proxycompany);
        }
        stmt.bindLong(18, entity.getHas_mv_mobile());
 
        String is_new = entity.getIs_new();
        if (is_new != null) {
            stmt.bindString(19, is_new);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(20, author);
        }
 
        String resource_type = entity.getResource_type();
        if (resource_type != null) {
            stmt.bindString(21, resource_type);
        }
 
        String has_filmtv = entity.getHas_filmtv();
        if (has_filmtv != null) {
            stmt.bindString(22, has_filmtv);
        }
 
        String all_artist_ting_uid = entity.getAll_artist_ting_uid();
        if (all_artist_ting_uid != null) {
            stmt.bindString(23, all_artist_ting_uid);
        }
 
        String artist_id = entity.getArtist_id();
        if (artist_id != null) {
            stmt.bindString(24, artist_id);
        }
 
        String versions = entity.getVersions();
        if (versions != null) {
            stmt.bindString(25, versions);
        }
 
        String publishtime = entity.getPublishtime();
        if (publishtime != null) {
            stmt.bindString(26, publishtime);
        }
 
        String style = entity.getStyle();
        if (style != null) {
            stmt.bindString(27, style);
        }
 
        String album_id = entity.getAlbum_id();
        if (album_id != null) {
            stmt.bindString(28, album_id);
        }
 
        String album_no = entity.getAlbum_no();
        if (album_no != null) {
            stmt.bindString(29, album_no);
        }
 
        String resource_type_ext = entity.getResource_type_ext();
        if (resource_type_ext != null) {
            stmt.bindString(30, resource_type_ext);
        }
 
        String del_status = entity.getDel_status();
        if (del_status != null) {
            stmt.bindString(31, del_status);
        }
 
        String hot = entity.getHot();
        if (hot != null) {
            stmt.bindString(32, hot);
        }
 
        String toneid = entity.getToneid();
        if (toneid != null) {
            stmt.bindString(33, toneid);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(34, title);
        }
 
        String pic_big = entity.getPic_big();
        if (pic_big != null) {
            stmt.bindString(35, pic_big);
        }
        stmt.bindLong(36, entity.getHavehigh());
        stmt.bindLong(37, entity.getCharge());
 
        String pic_radio = entity.getPic_radio();
        if (pic_radio != null) {
            stmt.bindString(38, pic_radio);
        }
        stmt.bindLong(39, entity.getLearn());
 
        String pic_s500 = entity.getPic_s500();
        if (pic_s500 != null) {
            stmt.bindString(40, pic_s500);
        }
 
        String all_artist_id = entity.getAll_artist_id();
        if (all_artist_id != null) {
            stmt.bindString(41, all_artist_id);
        }
 
        String pic_small = entity.getPic_small();
        if (pic_small != null) {
            stmt.bindString(42, pic_small);
        }
 
        String album_title = entity.getAlbum_title();
        if (album_title != null) {
            stmt.bindString(43, album_title);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ResultBean readEntity(Cursor cursor, int offset) {
        ResultBean entity = new ResultBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ssid
            cursor.getShort(offset + 1) != 0, // xuan
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // country
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // piao_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // album_1000_1000
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // korean_bb_song
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // pic_huge
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // all_rate
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // song_source
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // song_id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // album_500_500
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // rank
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // pic_premium
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // album_800_800
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // info
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // area
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // si_proxycompany
            cursor.getInt(offset + 17), // has_mv_mobile
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // is_new
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // author
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // resource_type
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // has_filmtv
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // all_artist_ting_uid
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // artist_id
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // versions
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // publishtime
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // style
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // album_id
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // album_no
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // resource_type_ext
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // del_status
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // hot
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // toneid
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // title
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // pic_big
            cursor.getInt(offset + 35), // havehigh
            cursor.getInt(offset + 36), // charge
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // pic_radio
            cursor.getInt(offset + 38), // learn
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // pic_s500
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // all_artist_id
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // pic_small
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42) // album_title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ResultBean entity, int offset) {
        entity.setSsid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setXuan(cursor.getShort(offset + 1) != 0);
        entity.setCountry(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPiao_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAlbum_1000_1000(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setKorean_bb_song(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPic_huge(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAll_rate(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSong_source(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSong_id(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAlbum_500_500(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setRank(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setPic_premium(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setAlbum_800_800(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setInfo(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setArea(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setSi_proxycompany(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setHas_mv_mobile(cursor.getInt(offset + 17));
        entity.setIs_new(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setAuthor(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setResource_type(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setHas_filmtv(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setAll_artist_ting_uid(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setArtist_id(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setVersions(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setPublishtime(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setStyle(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setAlbum_id(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setAlbum_no(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setResource_type_ext(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setDel_status(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setHot(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setToneid(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setTitle(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setPic_big(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setHavehigh(cursor.getInt(offset + 35));
        entity.setCharge(cursor.getInt(offset + 36));
        entity.setPic_radio(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setLearn(cursor.getInt(offset + 38));
        entity.setPic_s500(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setAll_artist_id(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setPic_small(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setAlbum_title(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ResultBean entity, long rowId) {
        entity.setSsid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ResultBean entity) {
        if(entity != null) {
            return entity.getSsid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ResultBean entity) {
        return entity.getSsid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
